# Generated by Django 4.0.4 on 2022-04-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.TextField(max_length=5000)),
                ('price', models.FloatField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product_thumnail', models.ImageField(upload_to='uploads/')),
                ('product_cover_image', models.ImageField(upload_to='uploads/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='bloger.category')),
            ],
        ),
    ]
